
version: '3.5'
services:
  db:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  web:
    build: .
    command: rake db:create
    command: rake db:migrate
    command: rake db:seed
    command: bundle exec rails webpacker:install
    command: bundle exec rails webpacker:check_yarn
    command: bundle exec rails webpacker:yarn_install
    command: bash -c "rm -rf tmp/ && bundle exec rails s -p 3000 -b '0.0.0.0' -e development"
    volumes:
      - ../:/apps
    ports:
      - "3001:3000"
    environment:
      - RAIL_ENV=development
      - DB_HOST=db
      - DB_NAME=common
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - ../:/apps
    depends_on:
      - web
    ports:
      - "3035:3035"