
version: '3.5'
services:
  db:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
        - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always
  webpack:
    build: .
    command: bash -c "./bin/webpack-dev-server"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - ../:/apps
    depends_on:
      - db
      - redis
    ports:
      - "3035:3035"
  web:
    build: .
    command: bash -c "bundle && rake db:migrate && rm -rf tmp/pids && bundle exec rails s -p 3000 -b '0.0.0.0' -e development"
    volumes:
      - ../:/apps
    ports:
      - "3001:3000"
    environment:
      - RAIL_ENV=development
      - DB_HOST=db
      - DB_NAME=common
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis://redis:6379
      - REMOTE_ASSETS_HOST=http://webpack:3035
    depends_on:
      - db
      - redis
      - webpack
  sidekiq:
    build: .
    command: bash -c "bundle && bundle exec sidekiq -C /apps/config/sidekiq.yml"
    environment:
      - RAIL_ENV=development
      - DB_HOST=db
      - DB_NAME=common
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis://redis:6379
    volumes:
      - ../:/apps
    depends_on:
      - db
      - redis
      - web