default: &default
  redis:
    url: <%= ENV.fetch('REDIS_HOST') { 'redis://localhost:6379/0' } %>
  assets_host: "http://127.0.0.1:3035"
  GCP:
    PROJECT_ID: "ecstatic-doodad-128103"
    GCS:
      BUCKET: "local_assets"
      CREDENTIALS: "<%= Rails.root.join("config/gcs_credentials.json") %>"
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default