default: &default
  GCP:
    PROJECT_ID: "ecstatic-doodad-128103"
    GCS:
      BUCKET: "local_assets"
      CREDENTIALS: "<%= Rails.root.join("config/gcs_credentials.json") %>"
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default