default: &default
  redis:
    url: <%= ENV.fetch('REDIS_HOST') { 'redis://localhost:6379/0' } %>
  assets_host: "http://127.0.0.1:3035"
  GCP:
    PROJECT_ID: "ecstatic-doodad-128103"
    GCS:
      BUCKET: "local_assets"
      CREDENTIALS: "<%= Rails.root.join("config/gcs_credentials.json") %>"
  mail:
    sender: "service@wowsofun.com"
    host: "smtp.mailgun.org"
    port: "2525"
    username: ""
    password: ""
    domain: "www.wowsofun.com"
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default