default: &default
  host: "127.0.0.1:3001"
  redis:
    url: <%= ENV.fetch('REDIS_HOST') { 'redis://localhost:6379/0' } %>
  assets_host: <%= ENV.fetch('ASSETS_HOST') { "http://127.0.0.1:3035" } %>
  #用來解 docker 內下載 css 檔案到 email 內用的 worker around! only development
  load_assets_content_from: <%= ENV.fetch('REMOTE_ASSETS_HOST') { "http://127.0.0.1:3035" } %>
  GCP:
    PROJECT_ID: "ecstatic-doodad-128103"
    GCS:
      BUCKET: "local_assets"
      CREDENTIALS: "<%= Rails.root.join("config/gcs_credentials.json") %>"
  mail:
    sender: "service@wowsofun.com"
    host: "smtp.mailgun.org"
    port: "2525"
    username: ""
    password: ""
    domain: "www.wowsofun.com"
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default