default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  username: postgres
  password: postgres
development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_development
test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>